# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\deep\gitcode\mediapipe_pyqt5_posture_detection\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.open_camera_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_camera_btn.setGeometry(QtCore.QRect(20, 20, 150, 46))
        self.open_camera_btn.setObjectName("open_camera_btn")
        self.close_camera_btn = QtWidgets.QPushButton(self.centralwidget)
        self.close_camera_btn.setEnabled(False)
        self.close_camera_btn.setGeometry(QtCore.QRect(220, 20, 150, 46))
        self.close_camera_btn.setObjectName("close_camera_btn")
        self.original_video_label = QtWidgets.QLabel(self.centralwidget)
        self.original_video_label.setGeometry(QtCore.QRect(20, 80, 400, 300))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.original_video_label.setFont(font)
        self.original_video_label.setFrameShape(QtWidgets.QFrame.Box)
        self.original_video_label.setAlignment(QtCore.Qt.AlignCenter)
        self.original_video_label.setObjectName("original_video_label")
        self.processed_video_label = QtWidgets.QLabel(self.centralwidget)
        self.processed_video_label.setGeometry(QtCore.QRect(480, 80, 400, 300))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.processed_video_label.setFont(font)
        self.processed_video_label.setFrameShape(QtWidgets.QFrame.Box)
        self.processed_video_label.setAlignment(QtCore.Qt.AlignCenter)
        self.processed_video_label.setObjectName("processed_video_label")
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "手势识别系统"))
        self.open_camera_btn.setText(_translate("MainWindow", "打开摄像头"))
        self.close_camera_btn.setText(_translate("MainWindow", "关闭摄像头"))
        self.original_video_label.setText(_translate("MainWindow", "等待摄像头开启"))
        self.processed_video_label.setText(_translate("MainWindow", "等待手势识别"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())