# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gesture_recognition.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.open_camera_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_camera_btn.setMinimumSize(QtCore.QSize(150, 40))
        self.open_camera_btn.setMaximumSize(QtCore.QSize(150, 40))
        self.open_camera_btn.setObjectName("open_camera_btn")
        self.horizontalLayout.addWidget(self.open_camera_btn)
        self.close_camera_btn = QtWidgets.QPushButton(self.centralwidget)
        self.close_camera_btn.setEnabled(False)
        self.close_camera_btn.setMinimumSize(QtCore.QSize(150, 40))
        self.close_camera_btn.setMaximumSize(QtCore.QSize(150, 40))
        self.close_camera_btn.setObjectName("close_camera_btn")
        self.horizontalLayout.addWidget(self.close_camera_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.original_video_label = QtWidgets.QLabel(self.centralwidget)
        self.original_video_label.setMinimumSize(QtCore.QSize(540, 400))
        self.original_video_label.setStyleSheet("border: 2px solid #cccccc; background-color: #f0f0f0;")
        self.original_video_label.setAlignment(QtCore.Qt.AlignCenter)
        self.original_video_label.setObjectName("original_video_label")
        self.horizontalLayout_2.addWidget(self.original_video_label)
        self.processed_video_label = QtWidgets.QLabel(self.centralwidget)
        self.processed_video_label.setMinimumSize(QtCore.QSize(540, 400))
        self.processed_video_label.setStyleSheet("border: 2px solid #cccccc; background-color: #f0f0f0;")
        self.processed_video_label.setAlignment(QtCore.Qt.AlignCenter)
        self.processed_video_label.setObjectName("processed_video_label")
        self.horizontalLayout_2.addWidget(self.processed_video_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "手势识别系统"))
        self.open_camera_btn.setText(_translate("MainWindow", "打开摄像头"))
        self.close_camera_btn.setText(_translate("MainWindow", "关闭摄像头"))
        self.original_video_label.setText(_translate("MainWindow", "等待摄像头开启..."))
        self.processed_video_label.setText(_translate("MainWindow", "等待手势识别..."))


# 添加更新视频帧的方法
class GestureRecognitionUI(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
    
    def update_original_frame(self, frame):
        """更新原始视频帧"""
        h, w, ch = frame.shape
        bytes_per_line = ch * w
        convert_to_qt_format = QtGui.QImage(frame.data, w, h, bytes_per_line, QtGui.QImage.Format_RGB888)
        pixmap = QtGui.QPixmap.fromImage(convert_to_qt_format)
        self.ui.original_video_label.setPixmap(pixmap)
    
    def update_processed_frame(self, frame):
        """更新处理后的视频帧"""
        h, w, ch = frame.shape
        bytes_per_line = ch * w
        convert_to_qt_format = QtGui.QImage(frame.data, w, h, bytes_per_line, QtGui.QImage.Format_RGB888)
        pixmap = QtGui.QPixmap.fromImage(convert_to_qt_format)
        self.ui.processed_video_label.setPixmap(pixmap)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = GestureRecognitionUI()
    ui.show()
    sys.exit(app.exec_())