# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1064, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.open_camera_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_camera_btn.setGeometry(QtCore.QRect(20, 20, 150, 46))
        self.open_camera_btn.setStyleSheet("background-color: #4CAF50; color: white; border-radius: 5px;")
        self.open_camera_btn.setObjectName("open_camera_btn")

        self.close_camera_btn = QtWidgets.QPushButton(self.centralwidget)
        self.close_camera_btn.setGeometry(QtCore.QRect(190, 20, 150, 46))
        self.close_camera_btn.setStyleSheet("background-color: #4CAF50; color: white; border-radius: 5px;")
        self.close_camera_btn.setObjectName("close_camera_btn")

        self.original_video_view = QtWidgets.QGraphicsView(self.centralwidget)
        self.original_video_view.setGeometry(QtCore.QRect(20, 80, 500, 400))
        self.original_video_view.setStyleSheet("border: 2px solid #cccccc; background-color: #f0f0f0;")
        self.original_video_view.setObjectName("original_video_view")

        self.processed_video_view = QtWidgets.QGraphicsView(self.centralwidget)
        self.processed_video_view.setGeometry(QtCore.QRect(610, 80, 500, 400))
        self.processed_video_view.setStyleSheet("border: 2px solid #cccccc; background-color: #f0f0f0;")
        self.processed_video_view.setObjectName("processed_video_view")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "手势识别系统"))
        self.open_camera_btn.setText(_translate("MainWindow", "打开摄像头"))
        self.close_camera_btn.setText(_translate("MainWindow", "关闭摄像头"))